name: Build & Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
      - name: Run Jest
        run: yarn test
      - name: Run Codecov
        run: yarn test-codecov
